version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:api --host 0.0.0.0
    volumes:
      - /code
    ports:
      - 8009:91
    environment:
      - DATABASE_URL=postgresql://postgres:sel@localhost:5432/farmerlynkz
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sel
      - POSTGRES_DB=farmerlynkz

volumes:
  postgres_data:  