--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3 (Ubuntu 13.3-1.pgdg20.04+1)
-- Dumped by pg_dump version 13.3 (Ubuntu 13.3-1.pgdg20.04+1)

-- Started on 2022-04-29 22:27:48 GMT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 208 (class 1259 OID 49256)
-- Name: department_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_type (
    id integer NOT NULL,
    title character varying
);


--
-- TOC entry 200 (class 1259 OID 49175)
-- Name: reset_password_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reset_password_codes (
    id integer NOT NULL,
    code character varying,
    user_id integer,
    user_email character varying,
    status boolean DEFAULT true NOT NULL,
    date_created date,
    date_modified date
);


--
-- TOC entry 206 (class 1259 OID 49226)
-- Name: reset_password_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reset_password_token (
    id integer NOT NULL,
    user_id integer,
    token character varying NOT NULL,
    date_created date
);


--
-- TOC entry 205 (class 1259 OID 49224)
-- Name: reset_password_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reset_password_token ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.reset_password_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 49192)
-- Name: revoked_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revoked_tokens (
    id integer NOT NULL,
    jti character varying,
    date_created date,
    date_modified date
);


--
-- TOC entry 201 (class 1259 OID 49190)
-- Name: revoked_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.revoked_tokens ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.revoked_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 49243)
-- Name: user_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_type (
    id integer NOT NULL,
    title character varying
);


--
-- TOC entry 204 (class 1259 OID 49213)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    staff_id integer NOT NULL,
    email character varying NOT NULL,
    password character varying,
    status boolean DEFAULT true,
    user_type_id integer,
    department_type_id integer
);


--
-- TOC entry 203 (class 1259 OID 49211)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 49276)
-- Name: users_staff_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN staff_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3059 (class 0 OID 49256)
-- Dependencies: 208
-- Data for Name: department_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.department_type (id, title) VALUES (1, 'Admin');


--
-- TOC entry 3051 (class 0 OID 49175)
-- Dependencies: 200
-- Data for Name: reset_password_codes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3057 (class 0 OID 49226)
-- Dependencies: 206
-- Data for Name: reset_password_token; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3053 (class 0 OID 49192)
-- Dependencies: 202
-- Data for Name: revoked_tokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3058 (class 0 OID 49243)
-- Dependencies: 207
-- Data for Name: user_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.user_type (id, title) VALUES (1, 'Admin');


--
-- TOC entry 3055 (class 0 OID 49213)
-- Dependencies: 204
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3066 (class 0 OID 0)
-- Dependencies: 205
-- Name: reset_password_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reset_password_token_id_seq', 1, false);


--
-- TOC entry 3067 (class 0 OID 0)
-- Dependencies: 201
-- Name: revoked_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.revoked_tokens_id_seq', 1, false);


--
-- TOC entry 3068 (class 0 OID 0)
-- Dependencies: 203
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- TOC entry 3069 (class 0 OID 0)
-- Dependencies: 209
-- Name: users_staff_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_staff_id_seq', 1, false);


--
-- TOC entry 2915 (class 2606 OID 49263)
-- Name: department_type department_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_type
    ADD CONSTRAINT department_type_pkey PRIMARY KEY (id);


--
-- TOC entry 2893 (class 2606 OID 49183)
-- Name: reset_password_codes reset_password_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_codes
    ADD CONSTRAINT reset_password_codes_pkey PRIMARY KEY (id);


--
-- TOC entry 2907 (class 2606 OID 49233)
-- Name: reset_password_token reset_password_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_token
    ADD CONSTRAINT reset_password_token_pkey PRIMARY KEY (id);


--
-- TOC entry 2901 (class 2606 OID 49199)
-- Name: revoked_tokens revoked_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revoked_tokens
    ADD CONSTRAINT revoked_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 2895 (class 2606 OID 49185)
-- Name: reset_password_codes ukey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_codes
    ADD CONSTRAINT ukey1 UNIQUE (code);


--
-- TOC entry 2897 (class 2606 OID 49187)
-- Name: reset_password_codes ukey2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_codes
    ADD CONSTRAINT ukey2 UNIQUE (user_id);


--
-- TOC entry 2899 (class 2606 OID 49189)
-- Name: reset_password_codes ukey3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_codes
    ADD CONSTRAINT ukey3 UNIQUE (user_email);


--
-- TOC entry 2903 (class 2606 OID 49223)
-- Name: users ukey4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukey4 UNIQUE (email);


--
-- TOC entry 2909 (class 2606 OID 49235)
-- Name: reset_password_token ukey5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_token
    ADD CONSTRAINT ukey5 UNIQUE (user_id);


--
-- TOC entry 2911 (class 2606 OID 49252)
-- Name: user_type ukey6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_type
    ADD CONSTRAINT ukey6 UNIQUE (title);


--
-- TOC entry 2917 (class 2606 OID 49265)
-- Name: department_type ukey7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_type
    ADD CONSTRAINT ukey7 UNIQUE (title);


--
-- TOC entry 2913 (class 2606 OID 49250)
-- Name: user_type user_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_type
    ADD CONSTRAINT user_type_pkey PRIMARY KEY (id);


--
-- TOC entry 2905 (class 2606 OID 49221)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2920 (class 2606 OID 49236)
-- Name: reset_password_token fkey1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reset_password_token
    ADD CONSTRAINT fkey1 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 2918 (class 2606 OID 49266)
-- Name: users fkey2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkey2 FOREIGN KEY (user_type_id) REFERENCES public.user_type(id) NOT VALID;


--
-- TOC entry 2919 (class 2606 OID 49271)
-- Name: users fkey3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkey3 FOREIGN KEY (department_type_id) REFERENCES public.department_type(id) NOT VALID;


-- Completed on 2022-04-29 22:27:48 GMT

--
-- PostgreSQL database dump complete
--

